# run_lab_report.ps1
# Automates the memory management lab and generates a report.

param (
    [int]$safeCount = 500000,
    [int]$leakCount = 500000
)

$reportFile = "LAB_RESULTS_AUTOMATED.md"
Write-Host "Starting Memory Management Lab Automation..."
Write-Host "This will generate: $reportFile"

# 1. Start Environment
Write-Host "Starting Docker container..."
docker-compose down
docker-compose up -d --build

# Wait for healthcheck
Write-Host "Waiting for container to be healthy..."
$healthy = $false
$retry = 0
while (-not $healthy -and $retry -lt 30) {
    $status = docker inspect --format='{{.State.Health.Status}}' xgboost-ml-demo-xgboost-demo-1
    if ($status -eq "healthy") {
        $healthy = $true
    } else {
        Start-Sleep -Seconds 2
        $retry++
    }
}

if (-not $healthy) {
    Write-Error "Container failed to start or become healthy."
    exit 1
}

$containerId = docker ps --filter "name=xgboost-ml-demo-xgboost-demo-1" --format "{{.ID}}"

# 2. Baseline
Write-Host "Collecting Baseline..."
$baselineRSS = (docker stats --no-stream $containerId --format "{{.MemUsage}}").Split(' ')[0]
$baselineNMT = docker exec $containerId jcmd 1 VM.native_memory summary

# 3. Safe Test
Write-Host "Running Safe Test ($safeCount requests)..."
Invoke-RestMethod -Method Post -Uri "http://localhost:8080/api/test/stress?count=$safeCount&leak=false"
Write-Host "Collecting Safe Test Metrics..."
$safeRSS = (docker stats --no-stream $containerId --format "{{.MemUsage}}").Split(' ')[0]
$safeNMT = docker exec $containerId jcmd 1 VM.native_memory summary

# 4. Leaky Test
Write-Host "Running Leaky Test ($leakCount requests)..."
Invoke-RestMethod -Method Post -Uri "http://localhost:8080/api/test/stress?count=$leakCount&leak=true"
Write-Host "Collecting Leaky Test Metrics..."
$leakyRSS = (docker stats --no-stream $containerId --format "{{.MemUsage}}").Split(' ')[0]
$leakyNMT = docker exec $containerId jcmd 1 VM.native_memory summary

# 5. Generate Report
$reportContent = @"
# Automated Lab Results Report
Generated on: $(Get-Date)

## 📊 Summary
| Phase | Requests | RSS (Real Memory) |
| :--- | :--- | :--- |
| **Baseline** | 0 | $baselineRSS |
| **Safe Test** | $safeCount | $safeRSS |
| **Leaky Test** | $leakCount | $leakyRSS |

## 🔍 Native Memory Tracking (NMT) Highlights

### Baseline Summary
$baselineNMT

### After Leaky Test
$leakyNMT

---
*Generated by run_lab_report.ps1*
"@

$reportContent | Out-File -FilePath $reportFile -Encoding utf8
Write-Host "Lab completed successfully. Results saved to $reportFile"
docker-compose down
